0.999-004

diff --git a/MaLARea/bin/eproof b/MaLARea/bin/eproof
--- a/MaLARea/bin/eproof
+++ b/MaLARea/bin/eproof
@@ -21,22 +21,25 @@ fi
 tmpfile=$TMPDIR/"eproof_"${host}"_"${pid}
 tmpfile2=$TMPDIR/"eprooftmp_"${host}"_"${pid}
 
-timeout=""
-
+status=0
 
 cleanup () 
 {  
     ulimit -S unlimited
     touch $tmpfile $tmpfile2
-    rm $tmpfile $tmpfile2
-    if [ "$timeout" = "" ] ; then
-        echo "# Cannot determine problem status: Terminated by signal. Cleaning up"
-    fi
-    exit 
+    rm -f $tmpfile $tmpfile2
+    exit $status
 } 
 
+xcpuhandler ()
+{
+    echo "# Cannot determine problem status: Terminated by signal. Cleaning up"
+    cleanup 
+}
+
+
 trap 'cleanup' EXIT
-trap 'cleanup' SIGXCPU
+trap 'xcpuhandler' SIGXCPU
 
 cat /dev/null > $tmpfile 
 cat /dev/null > $tmpfile2 
@@ -60,6 +63,10 @@ for argument in  "$@"; do
     elif [ "$argument" = "--print-statistics" ] ; then
 	print_stats=29
         print_res=6
+    elif [ "$argument" = "-V" -o "$argument" = "--version" ] ; then
+        $EXECPATH/eprover --version
+        $EXECPATH/epclextract --version
+        exit $?
     else
 	head=`echo "$argument"|cut -d= -f1`
 	head1=`echo "$argument"|cut -c1-2`
@@ -100,7 +107,8 @@ done
 print_tail=`expr $print_res + $print_stats`
 
 sh -c "$EXECPATH/eprover $newargs -l4 -R -o- --pcl-terms-compressed --pcl-compact> $tmpfile"
-$TAIL +60 $tmpfile > $tmpfile2
+status=$?
+$TAIL -60 $tmpfile > $tmpfile2
 searchtime=`cat $tmpfile2|grep "Total time"|cut -d: -f2|sed -e 's/[s ]//g'|cut -d. -f1`
 if [ "$searchtime" ]; then
     statusline=`grep -c 'No proof found!' $tmpfile2`
@@ -128,13 +136,12 @@ if [ "$searchtime" ]; then
     grep "# SZS status" $tmpfile2
     grep "# Failure"          $tmpfile2
     $EXECPATH/epclextract $format -f --competition-framing $tmpfile
+    status=$?
     $TAIL -$print_tail $tmpfile2
 else
     echo "# Cannot determine problem status within resource limit"
-    cleanup
 fi
-
-timeout="1"
+cleanup
 
 
 
